; PlatformIO Project Configuration File
; Bienenwaagendisplay - Wemos NodeMCU (ESP-12E), I2C LCD 16x2, HX711
; Board: NodeMCU v2 (ESP8266)

[env:nodemcuv2]
platform  = espressif8266
board     = nodemcuv2
framework = arduino
monitor_speed        = 115200
board_build.filesystem = littlefs

; Build-Flags
build_flags =
    -D CORE_DEBUG_LEVEL=3

; Bibliotheken
lib_deps =
    ; LCD I2C Display (16x2)
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

    ; HX711 Wägezellen-Verstärker
    bogde/HX711@^0.7.5

    ; MQTT
    knolleary/PubSubClient@^2.8

    ; JSON Verarbeitung
    bblanchon/ArduinoJson@^7.2.0

    ; DS18B20 Temperatursensor
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0

    ; OTA ist im ESP8266-Framework (ArduinoOTA) enthalten
